### ISSUE TITLE
Remote Control Effects

### ISSUE THREAD

**Issue by marcinn** [fx-planet/lwks-fx-bundle#2]
_From @FxSchrauber on April 12, 2018 21:38_

Hello,

When it was still about the presentation in the forum, there was the following idea regarding "Remote Control Effects":

> schrauber wrote:
> Control Effects: I think the handling is too complicated in practice. 
> Also some effects contain filter settings with unclear compatibility....

>jwrl wrote: 
>  I have a plan B: what about having a separate thread, with a link to it from the effects by category?

> schrauber wrote: That would be perfect.

**Issue 1:**
RC1_Remote_control.fx (maybe it also affects other effects?)?
`MagFilter = PYRAMIDALQUAD;`
Unclear compatibility (Is different from the  Cg 3.1 Reference Manual) 
It works with Windows, Intel HD Graphics 4600
Edit: Solved

**Issue 2:** Various effects
`AddressU = Clamp;   AddressV = Clamp;`
Possible solutions are known.
Edit: Solved

**Issue 3:** Various effects
Incompatible with Lightworks 14.5 GPU Precision Settings "**16-bit Floating Point**".
Suspected cause: Rounding error of the remote controller status value.
Solution: Change Code (use a tolerance range when checking the status value.)
Edit: Solved

_Copied from original issue: fx-planet/fxplanet#1_

**Comment by FxSchrauber** [comment]
I am currently editing the effects from the folder "Z-RC", in the GitHub branch "Remote-Control-fx"

**Comment by FxSchrauber** [comment]
**Issue 4:** (RC_Lift.fx  & RC_Lift_RGB.fx )

I notice now that these effects do something different than the effect name promises.
In fact, these effects change the offset. (Called "Brightness" in the Lightworks "Color Correction" effect).

**Comment by FxSchrauber** [comment]
Regarding Issue 4:
**RC_Lift.fx** has been replaced by **RC_Lift_20180418.fx**. 

The old RC_Lift.fx filed in an archive unterurdner.
This is available to the user in a separate category, in case old projects need this version.
This archive is just a try, not yet optimal. (would be to discuss).

**RC_Lift_RGB.fx** is not solved yet.

All effects from the category "Remote Control Color Grade" have now been moved to the subcategory "Color / Requires remote control".
Adapted effect descriptions, etc.

**Comment by FxSchrauber** [comment]
Regarding Issue 1:
Solved in effect **RC1_Remote_control.fx**, by reducing two shader runs to just one, etc.
The problem still exists in effect RC3001_Cyclic_Remote.fx

**Comment by FxSchrauber** [comment]
RC3001_Cyclic_Remote.fx  rewritten.

**Comment by FxSchrauber** [comment]
Solved
