### ISSUE TITLE
Determine what should be a unique key

### ISSUE THREAD

**Issue by marcinn** [fx-planet/lwks-fx-bundle#4]
Currently a FX filename (without path, i.e. without directory name where it is placed) should be unique.

**Comment by FxSchrauber** [comment]
Yes, for the installation in the Lightworks Effect Templates folder it is important that different effects have different file names.

It gets a bit more complex when managing different versions / updates of the same effect.

Case 1:
The changes should affect all existing projects / timelines that contain this effect.
The .fx file can simply be replaced with an .fx file of the same name in the Effect Templates folder. After restarting Lightworks, the code change would automatically be applied to all effects in existing timelines (without reinstalling).
Deviating from this:
Changes to the effect name, category, etc.
Changes to the effect setting parameters (for example, the adjustment range of the sliders).

Whether an automatic update of existing timelines makes sense and is desirable depends on the individual case.

Case 2:
If you want the change to work only on newly added effects, then the new .fx file would have to be installed under a different file man, leaving the old file unaltered.

**Comment by FxSchrauber** [comment]
Is it possible to change file names on GitHub without losing the version history?
Previously, I changed file names by creating or uploading a file, and deleted the old one.

**Comment by marcinn** [comment]
It should be doable https://blog.github.com/2013-03-15-moving-and-renaming-files-on-github/

**Comment by FxSchrauber** [comment]
Many Thanks

**Comment by FxSchrauber** [comment]
It would also be discussed how the homepage should be synced with GitHub.

After renaming an effect, there are two versions of this effect on the homepage, even if this file is no longer on GitHub. Of course, this also applies to completely withdrawn effects.
**Possible faulty effects remain on the homepage.**

Would it be better if only this would appear on the homepage, which is present at the time of the automatic update on GitHub?
