### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by marcinn** [fx-planet/lwks-fx-bundle#6]
Every fx should have `@license` attr defined. We should know how and when every FX can be used, and by who, and who and how can distribute it.

**Comment by FxSchrauber** [comment]
As for the code I created:
Freely usable, as easy as possible.
Ideal would be if others could use my code without source notes.
But I do not know whether it can be ensured without source notes that I and others can freely use the code in the future as well?
If anyone uses my code for commercial purposes I would not care, as long as I can continue to use and distribute my code for free.

Which would be the right license for that.

If I have used foreign code in my effect, then it gets more complicated. But this is rarely the case ("Kaleido turbine mixer") , or are only very short code fragments (rotation code of jwrl, etc.)
